name: Append New Data to MotherDuck Daily

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  append_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Latest DuckDB with MotherDuck
        run: |
          wget https://motherduck.com/download/duckdb-cli-linux-amd64 -O duckdb
          chmod +x duckdb
          sudo mv duckdb /usr/local/bin/

      - name: Verify DuckDB Version
        run: duckdb --version  # Ensure correct version is installed

      - name: Authenticate with MotherDuck
        run: |
          duckdb <<EOF
          INSTALL motherduck;
          LOAD motherduck;
          ATTACH 'md:your_database_name' AS md USING '${{ secrets.MOTHERDUCK_TOKEN }}';
          EOF

      - name: Append Only New Data to Tables
        run: |
          duckdb <<EOF
          ATTACH 'md:your_database_name' AS md;

          -- Ensure DuckDB always fetches the latest data (disable caching)
          SET enable_http_metadata_cache = false;
          SET enable_object_cache = false;

          -- Append new data for customer
          INSERT INTO customer
          SELECT customer_id, ls__customer_id__customer_name, customer_city, geo__customer_city__city_pushpin_longitude, geo__customer_city__city_pushpin_latitude, customer_country, customer_email, customer_state, customer_created_date, wdf__client_id
          FROM read_csv_auto('https://raw.githubusercontent.com/janpansky/demo_data/main/data/customer.csv') AS new
          WHERE new.customer_created_date > (SELECT COALESCE(MAX(customer_created_date), '1900-01-01') FROM customer);

          -- Append new data for monthly_inventory
          INSERT INTO monthly_inventory
          SELECT * 
          FROM read_csv_auto('https://raw.githubusercontent.com/janpansky/demo_data/main/data/monthly_inventory.csv') AS new
          WHERE new.date > (SELECT COALESCE(MAX(date), '1900-01-01') FROM monthly_inventory);

          -- Append new data for order_lines
          INSERT INTO order_lines
          SELECT * 
          FROM read_csv_auto('https://raw.githubusercontent.com/janpansky/demo_data/main/data/order_lines.csv') AS new
          WHERE new.date > (SELECT COALESCE(MAX(date), '1900-01-01') FROM order_lines);

          -- Append new data for returns
          INSERT INTO returns
          SELECT * 
          FROM read_csv_auto('https://raw.githubusercontent.com/janpansky/demo_data/main/data/returns.csv') AS new
          WHERE new.date > (SELECT COALESCE(MAX(date), '1900-01-01') FROM returns);
          EOF
