name: Append New Data to MotherDuck Daily

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  append_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install DuckDB v1.2.0
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v1.2.0/duckdb_cli-linux-amd64.zip
          unzip duckdb_cli-linux-amd64.zip
          chmod +x duckdb
          sudo mv duckdb /usr/local/bin/

      - name: Authenticate with MotherDuck
        run: |
          duckdb -c "
          INSTALL motherduck;
          LOAD motherduck;
          CALL md_auth('${{ secrets.MOTHERDUCK_TOKEN }}');
          "

      - name: Append Only New Data to Tables
        run: |
          duckdb -c "
          ATTACH 'md:your_database_name' AS md;

          -- Ensure DuckDB always fetches the latest data (disable caching)
          SET enable_http_metadata_cache = false;
          SET enable_object_cache = false;

          -- Append new data for customer
          INSERT INTO md.customer
          SELECT *
          FROM read_csv_auto('https://raw.githubusercontent.com/your_username/your_repository/main/data/customer.csv') AS new
          WHERE new.customer_created_date > (SELECT COALESCE(MAX(customer_created_date), '1900-01-01') FROM md.customer);

          -- Append new data for monthly_inventory
          INSERT INTO md.monthly_inventory
          SELECT *
          FROM read_csv_auto('https://raw.githubusercontent.com/your_username/your_repository/main/data/monthly_inventory.csv') AS new
          WHERE new.date > (SELECT COALESCE(MAX(date), '1900-01-01') FROM md.monthly_inventory);

          -- Append new data for order_lines
          INSERT INTO md.order_lines
          SELECT *
          FROM read_csv_auto('https://raw.githubusercontent.com/your_username/your_repository/main/data/order_lines.csv') AS new
          WHERE new.date > (SELECT COALESCE(MAX(date), '1900-01-01') FROM md.order_lines);

          -- Append new data for returns
          INSERT INTO md.returns
          SELECT *
          FROM read_csv_auto('https://raw.githubusercontent.com/your_username/your_repository/main/data/returns.csv') AS new
          WHERE new.date > (SELECT COALESCE(MAX(date), '1900-01-01') FROM md.returns);
          "
